# Generated by Django 5.2.5 on 2025-08-26 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ongs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrecadado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('urgencia', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ongs.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão de Crédito'), ('BOLETO', 'Boleto')], max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=50)),
                ('tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_doacao', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
