# Generated by Django 5.2.5 on 2025-08-26 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('status_verificacao', models.CharField(choices=[('EM_ANALISE', 'Em Análise'), ('VERIFICADO', 'Verificado'), ('RECUSADO', 'Recusado')], default='EM_ANALISE', max_length=50)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
